// Package fallback implements a non-eBPF userspace load balancer that works
// without any Linux capabilities.
//
// ─── THE PRIVILEGE TRAP ──────────────────────────────────────────────────────
// Omega-LB's eBPF data plane requires three Linux capabilities:
//
//   CAP_BPF      — load eBPF programs and create maps
//   CAP_NET_ADMIN — attach sock_ops to cgroup, set socket options
//   CAP_SYS_ADMIN — pin maps to bpffs, access /sys/fs/bpf
//
// In most enterprise Kubernetes clusters, these capabilities are blocked by
// security policy (PodSecurityAdmission, OPA/Gatekeeper, or legacy PSP).
// Requesting them triggers a security review that can take months to approve.
// Even with approval, some managed clusters (GKE Autopilot, EKS Fargate) will
// never permit them.
//
// This fallback mode provides production-viable load balancing with ZERO
// capabilities by generating NGINX upstream configuration from the same
// ring.Manager that drives the eBPF path.
//
// ─── WHAT YOU GET IN FALLBACK MODE ───────────────────────────────────────────
//   • Dynamic NGINX upstream config generated from the H&A ring
//   • Round-robin and weighted upstreams; hot-reload on backend change
//   • Health check pass-through to NGINX's active health module
//   • No CAP_BPF, no CAP_NET_ADMIN, no CAP_SYS_ADMIN required
//   • Runs as a non-root user (UID 1000) with no hostNetwork
//
// ─── WHAT YOU LOSE IN FALLBACK MODE ─────────────────────────────────────────
//   • eBPF kernel-level dispatch (~4µs overhead vs ~40ns for eBPF sockops)
//   • Kernel-side circuit breaker (50ms detection → replaced by 2s health check)
//   • Per-CPU map metrics (replaced by NGINX access log parsing)
//   • NUMA-aware ring lookup, Maglev O(1) table
//
// ─── UPGRADE PATH ─────────────────────────────────────────────────────────────
// When your cluster approves the capabilities (or you move to bare-metal):
//   1. Set OMEGALB_MODE=ebpf in the DaemonSet env
//   2. Switch to daemonset-restricted.yaml or daemonset.yaml
//   3. The ring.Manager state is preserved; no traffic interruption
//
// ─── HOW NGINX RELOAD WORKS ──────────────────────────────────────────────────
// NGINX re-reads its config on SIGHUP without dropping connections.  The
// fallback backend calls `nginx -s reload` after writing a new upstream config.
// Typical reload latency: 50–100ms.  No connections are dropped.
package fallback

import (
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"sync"
	"text/template"
	"time"

	"go.uber.org/zap"
)

// BackendEntry describes a backend server for NGINX configuration.
type BackendEntry struct {
	Address string  // host:port
	Weight  int     // relative weight (proportional to vnode count)
	Down    bool    // true = mark as down in NGINX upstream
}

// NginxWriter generates NGINX upstream configuration from the ring's backend
// state and reloads NGINX when the topology changes.
//
// It watches for topology changes via a channel and debounces rapid changes
// (e.g. multiple backends recovering simultaneously) into a single reload.
type NginxWriter struct {
	mu           sync.Mutex
	configDir    string      // directory for omega-lb-upstream.conf
	nginxBin     string      // path to nginx binary (default: "nginx")
	reloadDelay  time.Duration
	pendingWrite bool
	log          *zap.Logger
}

// NewNginxWriter creates a writer that generates nginx upstream configs into configDir.
// nginxBin defaults to "nginx" if empty.
func NewNginxWriter(configDir, nginxBin string, log *zap.Logger) (*NginxWriter, error) {
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return nil, fmt.Errorf("fallback: mkdir %s: %w", configDir, err)
	}
	if nginxBin == "" {
		nginxBin = "nginx"
	}
	return &NginxWriter{
		configDir:   configDir,
		nginxBin:    nginxBin,
		reloadDelay: 200 * time.Millisecond, // debounce window
		log:         log,
	}, nil
}

// upstreamTemplate generates the NGINX upstream block from backend entries.
var upstreamTemplate = template.Must(template.New("upstream").Parse(`
# Generated by Omega-LB fallback mode — do not edit by hand.
# Regenerated on topology change; reload triggered via SIGHUP.
upstream omega_lb_backends {
    least_conn;  # approximates H&A bounded-load; upgrade to eBPF mode for true H&A
{{- range .Backends }}
{{- if .Down }}
    server {{ .Address }} weight={{ .Weight }} down;
{{- else }}
    server {{ .Address }} weight={{ .Weight }};
{{- end }}
{{- end }}

    keepalive 256;
    keepalive_requests 10000;
    keepalive_timeout 60s;
}
`))

// WriteConfig renders the NGINX upstream config and writes it to configDir.
// Returns the path of the written file.
func (w *NginxWriter) WriteConfig(backends []BackendEntry) (string, error) {
	if len(backends) == 0 {
		return "", fmt.Errorf("fallback: no backends; refusing to write empty upstream config")
	}

	type data struct{ Backends []BackendEntry }
	var sb strings.Builder
	if err := upstreamTemplate.Execute(&sb, data{Backends: backends}); err != nil {
		return "", fmt.Errorf("fallback: render template: %w", err)
	}

	path := filepath.Join(w.configDir, "omega-lb-upstream.conf")
	// Write atomically (write to tmp, rename) to avoid NGINX reading a
	// partially-written file during reload.
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, []byte(sb.String()), 0644); err != nil {
		return "", fmt.Errorf("fallback: write %s: %w", tmp, err)
	}
	if err := os.Rename(tmp, path); err != nil {
		return "", fmt.Errorf("fallback: rename upstream config: %w", err)
	}
	return path, nil
}

// ReloadNginx sends SIGHUP to NGINX (nginx -s reload).
// NGINX re-reads configuration without dropping existing connections.
func (w *NginxWriter) ReloadNginx() error {
	cmd := exec.Command(w.nginxBin, "-s", "reload")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("fallback: nginx reload failed: %w (output: %s)", err, strings.TrimSpace(string(out)))
	}
	w.log.Info("nginx upstream reloaded", zap.String("output", strings.TrimSpace(string(out))))
	return nil
}

// Run watches the updates channel for topology change notifications.
// Each notification triggers a debounced config rewrite + NGINX reload.
// Returns when ctx is cancelled.
func (w *NginxWriter) Run(ctx context.Context, updates <-chan []BackendEntry) error {
	var (
		pending   []BackendEntry
		reloadAt  = time.Time{}
		timer     *time.Timer
	)

	flushConfig := func() {
		if pending == nil {
			return
		}
		backends := pending
		pending = nil
		path, err := w.WriteConfig(backends)
		if err != nil {
			w.log.Error("fallback: failed to write nginx config", zap.Error(err))
			return
		}
		w.log.Info("fallback: wrote nginx upstream config",
			zap.String("path", path),
			zap.Int("backends", len(backends)),
		)
		if err := w.ReloadNginx(); err != nil {
			w.log.Error("fallback: nginx reload failed", zap.Error(err))
		}
	}

	for {
		select {
		case <-ctx.Done():
			return ctx.Err()

		case backends, ok := <-updates:
			if !ok {
				return nil
			}
			pending = backends
			// Debounce: if another update arrives within reloadDelay, reset timer.
			reloadAt = time.Now().Add(w.reloadDelay)
			if timer != nil {
				timer.Stop()
			}
			timer = time.AfterFunc(w.reloadDelay, func() {
				w.mu.Lock()
				defer w.mu.Unlock()
				if time.Now().After(reloadAt) {
					flushConfig()
				}
			})

		case <-func() <-chan time.Time {
			if timer != nil {
				return timer.C
			}
			return nil
		}():
			w.mu.Lock()
			flushConfig()
			w.mu.Unlock()
		}
	}
}
